//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_itog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Products
    {
        public int ID_Goods_Products { get; set; }
        public int Good_ID { get; set; }
        public int Product_ID { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Products Products { get; set; }
    }
}
