//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_itog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SUSHIK_STOREEntities4 : DbContext
    {
        public SUSHIK_STOREEntities4()
            : base("name=SUSHIK_STOREEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorization_Clients> Autorization_Clients { get; set; }
        public virtual DbSet<Autorization_Employees> Autorization_Employees { get; set; }
        public virtual DbSet<Checks> Checks { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<Goods_Products> Goods_Products { get; set; }
        public virtual DbSet<Goods_Types> Goods_Types { get; set; }
        public virtual DbSet<Job_Title> Job_Title { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payment_Types> Payment_Types { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Statuss> Statuss { get; set; }
    }
}
